### ISSUE TITLE
Attribution OpenStreetMap à améliorer

### ISSUE THREAD

**Issue by Jean-BaptisteC** [fab-geocommuns/RNB-site#147]
Bonjour,

L'attribution OpenStreetMap n'est pas visible par défaut sur desktop, il est nécessaire d'utiliser l'ascenseur. 
Et sur mobile, l'attribution est complétement absente pouvez-vous faire le nécessaire ?
Merci

https://github.com/osm-fr/attributions/issues/472

**Comment by Jean-BaptisteC** [comment]
CC @bbaret

**Comment by bbaret** [comment]
Merci pour ton retour !

**Comment by Jean-BaptisteC** [comment]
C'est tout bon merci pour ta réactivité, je ferme le ticket de notre côté
