### ISSUE TITLE
Mail de contact non fonctionnel

### ISSUE THREAD

**Issue by Jean-BaptisteC** [fab-geocommuns/RNB-site#154]
Mail de contact non fonctionnel à cette adresse https://rnb.beta.gouv.fr/a-propos
![image](https://github.com/user-attachments/assets/319ab613-5656-42b9-babc-9f1d4c68b6d8)

https://github.com/fab-geocommuns/RNB-site/blob/82e992dbb18c1564d4342f2809bead6bc75e248c/app/(normalLayout)/a-propos/page.tsx#L117

**Comment by Jean-BaptisteC** [comment]
CC @pauletienney

**Comment by pauletienney** [comment]
Merci Jean-Baptiste.
Nous venons de tester l'adresse email et elle reçoit bien les emails.
Quel problème as-tu constaté ?

**Comment by Jean-BaptisteC** [comment]
Le mailto n'est pas fonctionnel cliquer sur le lien retourne une erreur 404 :)
