### ISSUE TITLE
[Sponsors] Logo ADEME avec Marianne

### ISSUE THREAD

**Issue by fe51** [fab-geocommuns/RNB-site#30]
Le logo officiel de l'ADEME ne se promène jamais sans la Marianne :)

<img width="235" alt="image" src="https://github.com/fab-geocommuns/RNB-site/assets/55736935/cfbe71e0-46e0-46b9-b3df-3da8cba58eda">

[Un exemple de fichier avec les deux dispo ici
](https://upload.wikimedia.org/wikipedia/fr/6/67/Logo_ADEME.svg)

Merci bcp !

**Comment by fchabouis** [comment]
j'ai l'impression que c'est bon @fe51 , c'était pour le bas de la page d'accueil ?
On a le bon logo, Paul a dû le faire.
