### ISSUE TITLE
[Affichage Carte] Taille de la carte réduite sur la hauteur.  

### ISSUE THREAD

**Issue by fe51** [fab-geocommuns/RNB-site#31]
Hello, 

Pb d'affichage de la carte, qui lorsque j'arrive sur la page, ne prend pas l'espace dédié (voir screenshots ci dessous)

En réduisant la taille de la fenêtre, on récupère le fonctionnement attendu.

Bug rencontré sur safari et google chrome sur macbookpro 14". (je partage les versions si besoins)

Espérons que les évolutions pour rendre al carte mobile friendly vont aussi solutionner ce petit pb d'affichage :)
A dispo pour en discuter ! Merci !
![image](https://github.com/fab-geocommuns/RNB-site/assets/55736935/961d2daf-4ca7-4658-9417-34e677a34cba)
![image](https://github.com/fab-geocommuns/RNB-site/assets/55736935/49a5b807-e16e-419e-b45a-16da98dbf88e)

**Comment by pauletienney** [comment]
Oui c'est vu, je vais régler ça. Merci pour le ticket.
