### ISSUE TITLE
[Carte] Barre de recherche : Erreur en cherchant un id non existant

### ISSUE THREAD

**Issue by fe51** [fab-geocommuns/RNB-site#68]
Hello, 

La barre de recherche permet d'effectuer une recherche d'adresse ou via un id-bâtiment. 
Il s'avère que si l'on rentre un rnb-id qui n'existe pas, on tombe sur l'erreur (404 coté server ) suivante :
![image](https://github.com/fab-geocommuns/RNB-site/assets/55736935/9b35647c-c9be-4463-b61a-49356521635d)

A priori, c'est le fait de faire une recherche en utilisant la regex pour détecter un id bâtiment dans le champ de recherche, avec un id qui n'existe pas qui amène à ce bug.

On le reproduit par exemple en cherchant : `mich-mich-1234` mais on obtient bien un résultat, évidement absurde en rentrant `mich-mich-12345`

A dispo pour en discuter !

PS : J'ai rencontré le pb suite à la recherche d'un rnb-id qui n'existe plus suite à notre fixe la semaine dernière.

**Comment by fchabouis** [comment]
j'étais venu signaler la même chose :)
